system: mothership-assistant

components:
  ui:
    name: mothership-assistant-ui

    affinity: null

    image:
      repository: gitea.pixelparasol.com/nathan/mothership-assistant/ui
      tag: "latest"
      imagePullPolicy: "Always"
      imagePullSecrets: "gitea-auth"

    ingress:
      tls: true
      domain: games.nathanbstanley.com
      path: /
      className: "nginx"
      port: 80

    service:
      type: ClusterIP
      ports:
        - protocol: TCP
          port: 80
          targetPort: 80
          name: http

    deployment:
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"

    volumes:
      - name: nginx-configmap
        type: configMap
        mountPath: "/etc/nginx/conf.d/default.conf"
        subPath: "default.conf"

  # api:
  #   name: mothership-assistant-api

  #   affinity: null

  #   secrets:
  #     KEYCLOAK_SESSION_SECRET: "" # use --set components.api.secrets.KEYCLOAK_SESSION_SECRET="string" with helm to set or it will default to "initial" OR keep the set value if the secret exists

  #   image:
  #     repository: gitea.pixelparasol.com/nathan/mothership-assistant/api
  #     tag: "latest"
  #     imagePullPolicy: "Always"
  #     imagePullSecrets: "gitea-auth"

  #   ingress:
  #     tls: false
  #     domain: games.nathanbstanley.com
  #     path: /api
  #     className: "nginx"
  #     port: 80

  #   service:
  #     type: ClusterIP
  #     ports:
  #       - protocol: TCP
  #         port: 80
  #         targetPort: 3000
  #         name: http

  #   deployment:
  #     resources:
  #       limits:
  #         memory: "128Mi"
  #         cpu: "500m"
  #     env:
  #       - name: CORS_URLS
  #         value: "https://games.nathanbstanley.com"
  #       - name: PORT
  #         value: "3000" # Yes, this must be a string
  #       - name: REDIS_HOST
  #         value: "redis-service.mothership-assistant.svc.cluster.local"
  #       - name: REDIS_PORT
  #         value: "6379" # Yes, this must be a string
  #       - name: KEYCLOAK_REALM
  #         value: "mothership-assistant"
  #       - name: KEYCLOAK_AUTH_SERVER_URL
  #         value: "https://auth.pixelparasol.com"
  #       - name: KEYCLOAK_CLIENT_ID
  #         value: "mothership-assistant-api-client"
  #       - name: POSTGRES_HOST # Could put in db secrets, but db cluster does not need these values
  #         value: "postgres-service.mothership-assistant.svc.cluster.local"
  #       - name: POSTGRES_PORT # Same as POSTGRES_HOST
  #         value: "5432" # Yes, this must be a string
  #       - name: POSTGRES_URL
  #         value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_NAME)?schema=public"

  #     envFrom:
  #       - secretRef:
  #           name: mothership-assistant-api
  #       - secretRef:
  #           name: postgres
  #       - secretRef:
  #           name: redis

  # db:
  #   name: postgres

  #   affinity: null

  #   secrets:
  #     POSTGRES_USER: "" # As above
  #     POSTGRES_PASSWORD: "" # As above
  #     POSTGRES_NAME: "" # As above

  #   image:
  #     repository: postgres
  #     tag: alpine
  #     imagePullPolicy: "Always"

  #   service:
  #     type: ClusterIP
  #     ports:
  #       - protocol: TCP
  #         port: 5432
  #         targetPort: 5432
  #         name: redis

  #   volumes:
  #     - name: database-pv
  #       storageClassName: standard
  #       reclaimPolicy: Retain
  #       capacity:
  #         storage: 1Gi
  #       accessModes:
  #         - ReadWriteOnce
  #       hostPath: "/mnt/mothership-assistant/database"
  #       containerMountPath: "/var/lib/postgresql/data"

  #   deployment:
  #     envFrom:
  #       - secretRef:
  #           name: postgres

  # redis:
  #   name: redis

  #   affinity: null

  #   secrets:
  #     REDIS_PASSWORD: "" # use --set components.redis.secrets.REDIS_PASSWORD="string" with helm to set or it will default to "initial" OR keep the set value if the secret exists

  #   image:
  #     repository: redis
  #     tag: alpine
  #     imagePullPolicy: "Always"
  #     imagePullSecrets: "gitea-auth"

  #   service:
  #     type: ClusterIP
  #     ports:
  #       - protocol: TCP
  #         port: 6379
  #         targetPort: 6379
  #         name: redis

  #   deployment:
  #     envFrom:
  #       - secretRef:
  #           name: redis
  #     command: ["sh", "-c"]
  #     args:
  #       - redis-server --requirepass $REDIS_PASSWORD

backups:
  enabled: false
  image: alpine
  nas_ip: 192.168.1.12
  system_name: "mothership-assistant"
  volumes:
    - pvc_name: mothership-assistant-postgres-pvc
      enabled: true
      nas_path: /volume1/k8s-nfs-pv
      schedule: "0 0 * * 0" # Every Sunday at Midnight 0 0 * * 0
      retention: 4
